fix: sops decrypt failing

diff --git a/.github/workflows/ci-deploy.yml b/.github/workflows/ci-deploy.yml
--- a/.github/workflows/ci-deploy.yml
+++ b/.github/workflows/ci-deploy.yml
@@ -83,17 +83,21 @@ jobs:
 
       - name: Pull image and start
         uses: appleboy/ssh-action@v0.1.8
-        env:
-          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
           passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
           port: ${{ secrets.SERVER_SSH_PORT }}
-          envs: SOPS_AGE_KEY
           script: |
             set -euo pipefail
+
+            export SOPS_AGE_KEY_FILE="/etc/sops/age/key.txt"
+
+            if [ ! -f "$SOPS_AGE_KEY_FILE" ]; then
+              echo "SOPS age key file not found at $SOPS_AGE_KEY_FILE"
+              exit 1
+            fi
 
             cd "/containers/${{ github.repository }}"
 
